services:
  analysis-env:
    image: justintrenchcoat/milestone_1
    platform: linux/amd64
    ports:
      - "8787:8787"
    volumes:
    - .:/home/rstudio/work
    environment: 
      PASSWORD: "password"